### ISSUE TITLE
Área de controle do usuário (visualizar usuário logado, fazer logout)

### ISSUE THREAD

**Issue by studiojms** [Synchro-TEC/apollo-11#38]
Seria interessante ter um componente que possa mostrar os dados do usuário logado, bem como permitir que o usuário possa fazer logoff da aplicação (de preferência que a url de logoff seja customizada, pois cada aplicação pode possuir um endpoint diferente para tal ação).

**Comment by marcio** [comment]
Discussão aberta na issue #44
